name: GitHub CIS
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types: released

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        shell: pwsh
        run: |
          $msbuildPath = Split-Path (& "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -requires Microsoft.Component.MSBuild -find MSBuild\Current\Bin\amd64\MSBuild.exe | Select-Object -First 1) -Parent
          $env:PATH = $msbuildPath + ';' + $env:PATH
          .\build.ps1

      - name: Upload Build Artifacts
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v3
        with:
          name: de4dot-artifacts
          path: |
            Release/net35
            Release/net45
            publish-netcoreapp2.1
            publish-netcoreapp3.1
